### ISSUE TITLE
Postman collections format v2.1 support

### ISSUE THREAD

**Issue by oakesville** [limberest/limberest-js#5]
Here's what a request URL looks like now:
```json
"url": {
	"raw": "{{base-url}}/movies/{{id}}",
	"host": [
		"{{base-url}}"
	],
	"path": [
		"movies",
		"{{id}}"
	]
}
```

**Comment by rwhitehead64** [comment]
Thanks, Jeans.

-------- Original message --------From: Donald Oakes <notifications@github.com> Date: 10/6/17  7:45 PM  (GMT-06:00) To: limberest/limberest-js <limberest-js@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [limberest/limberest-js] Postman collections format v2.1 support (#5) 
Here's what a request URL looks like now:
"url": {
	"raw": "{{base-url}}/movies/{{id}}",
	"host": [
		"{{base-url}}"
	],
	"path": [
		"movies",
		"{{id}}"
	]
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/limberest/limberest-js","title":"limberest/limberest-js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/limberest/limberest-js"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Postman collections format v2.1 support (#5)"}],"action":{"name":"View Issue","url":"https://github.com/limberest/limberest-js/issues/5"}}}

**Comment by oakesville** [comment]
Fixed.
